include ../make/general.make
include ../make/autoprereq.make
include ../make/asf.make
include $(BUILDDIR)/autoprereq/test.d
include $(BUILDDIR)/autoprereq/$(subst ..,UP,../file.d)
all: test.o ../file.o
